version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      DB_SSLMODE: disable
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3-alpine3.20
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
      TZ: "Asia/Tokyo"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./_scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
