services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      ENV: ${ENV}
      API_PORT: ${API_PORT}
      READ_TIMEOUT: ${READ_TIMEOUT}
      WRITE_TIMEOUT: ${WRITE_TIMEOUT}
      INSTANCE_UNIX_SOCKET: ${INSTANCE_UNIX_SOCKET}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3-alpine3.20
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./_scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
