name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main

env:
  ARTIFACT_REGISTRY_LOCATION: asia-northeast1
  PROJECT_ID: coworker-match
  ARTIFACT_REGISTRY_REPO: cwm-api-dev-repo
  ARTIFACT_REGISTRY_IMAGE: cwm-api-dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.ARTIFACT_REGISTRY_IMAGE }}:${{ github.sha }}" .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push "${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.ARTIFACT_REGISTRY_IMAGE }}:${{ github.sha }}"
